version: "3"
services:
  api-rest:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: api-rest-123
      DB_NAME: api-rest
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: api-rest-123
      MYSQL_DATABASE: api-rest
    volumes:
      - ./db_data:/var/lib/mysql
